[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
base = "dark"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#141720"
primaryColor = "#00e676"
textColor = "#e0e0e0"
